repos:
  - repo: local
    hooks:
    -   id: black 
        name: black
        entry: black
        language: system
        types: [python] 
    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
        - --errors-only
    -   id: pytest
        name: pytest
        entry: pytest
        language: system
        types: [python]
        args:
        - --quiet
